### ISSUE TITLE
this is not work

### ISSUE THREAD

**Issue by vanillla1** [qbcore-framework/qbcore-framework.github.io#1]
https://github.com/qbcore-framework/qbcore-framework.github.io/blob/main/client/functions/_sidebar.md

and can add document for add new ped to qbcore ?

**Comment by BombayV** [comment]
I'm sorry, I don't understand what you mean. Could you be more specific and maybe add a better description?

**Comment by BerkieBb** [comment]
We don't have any functions for adding new peds, but @BombayV he means the sidebar doesn't work, I think it may be the links that don't bring you to the right place

**Comment by BombayV** [comment]
It seems to work fine.
