### ISSUE TITLE
Cannot join discord?

### ISSUE THREAD

**Issue by IdrisDose** [qbcore-framework/qbcore-framework.github.io#4]
Hey, I tried to join your discord and it just times out and kicks me/crashed discord.

https://discord.gg/zUdDccY5Pt ?

**Comment by BombayV** [comment]
If you cannot join, then you may be banned.

1) You are in leaking servers.
2) You have been banned before.
3) You're already in the discord.

**Comment by IdrisDose** [comment]
So, I can click the link the app loads for a split second, and discord crashes.

It doesn't swap to the server, it doesn't post any message or any other display, I've tried with an alt that's only in my personal discords and it does the same thing.

**Comment by IdrisDose** [comment]
Joined via web browser rather than using application, all sorted.
